universe = vanilla

executable = MAG_kallisto.sh
arguments = $(sample)

#REQUIREMENTS:

Requirements = (OpSys == "LINUX") && (OpSysMajorVer == 9) && (Target.HasCHTCStaging == true)

transfer_input_files = PROG_instl/OS9/kallisto-v0.50.1.tar.gz, \
                       PROG_instl/python-3.8.tar.gz, \
                       PROG_instl/python-3.8-packages.tar.gz

should_transfer_files = YES
when_to_transfer_output = ON_EXIT



log = MAG_kallisto/$(sample).log
error = MAG_kallisto/$(sample).error
output = MAG_kallisto/$(sample).out

request_memory = 64GB
request_disk = 64GB
request_cpus = 32

queue sample from(
102
103
104
107
109
110
111
113
115
116
)
