universe = vanilla

executable = WGS_removeHostRead.sh
arguments = $(sample)

#REQUIREMENTS:

Requirements = (OpSys == "LINUX") && (OpSysMajorVer == 9) && (Target.HasCHTCStaging == true)

transfer_input_files = PROG_instl/bowtie2-2.3.4-linux-x86_64.zip, \
                       PROG_instl/OS9/samtools-1.19.tar.gz, \
                       PROG_instl/bedtools2-2.28.0.tar.gz, \
                       PROG_instl/python-3.8.tar.gz, \
                       PROG_instl/python-3.8-packages.tar.gz

should_transfer_files = YES
when_to_transfer_output = ON_EXIT


log = MARS_WGS/rmHostReads/$(sample).log
error = MARS_WGS/rmHostReads/$(sample).error
output = MARS_WGS/rmHostReads/$(sample).out

request_memory = 32GB
request_disk = 128GB
request_cpus = 4

queue sample from(
102
103
104
107
109
110
111
113
115
116
)
